"""
scripts/export_lora_ct2.py

Merge a LoRA adapter into the base Whisper model and export to CTranslate2
format so it can be loaded by faster-whisper (the same engine used by WhisperX).

This gives the LoRA-enhanced model the full faster-whisper inference pipeline:
  - Beam search with temperature fallback
  - VAD-based segmentation
  - Proper capitalization and punctuation post-processing
  - initial_prompt / hotword injection
  - Identical output format to base WhisperX

Without this step the PEFT HuggingFace model runs through a simpler HF
generate() path that produces noisier output (lowercase, no punctuation,
no temperature fallback) even with beam search enabled.

Usage:
    python scripts/export_lora_ct2.py --provider general
    python scripts/export_lora_ct2.py --provider dr_faraz_rahman --quantization int8

Output:
    models/whisper_ct2/{provider_id}/   — faster-whisper compatible directory
    models/whisper_ct2/{provider_id}/processor/  — tokenizer + feature extractor

The WhisperXLoRAServer will prefer this CTranslate2 model when it exists,
falling back to the HF PEFT path only if the ct2 export is absent.
"""

from __future__ import annotations

import argparse
import logging
import shutil
import sys
import tempfile
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)

ROOT = Path(__file__).parent.parent
LORA_DIR = ROOT / "models" / "whisper_lora"
CT2_DIR  = ROOT / "models" / "whisper_ct2"
BASE_MODEL = "openai/whisper-large-v3"


def export(provider_id: str, quantization: str = "float16") -> Path:
    """
    1. Load base WhisperForConditionalGeneration
    2. Load LoRA adapter via PEFT
    3. Merge adapter weights into base (merge_and_unload)
    4. Save merged HF model to a temp directory
    5. Convert to CTranslate2 with ct2-transformers-converter
    6. Copy processor (tokenizer + feature extractor) alongside
    """
    import torch
    from transformers import WhisperForConditionalGeneration, WhisperProcessor
    from peft import PeftModel

    adapter_path = LORA_DIR / provider_id
    if not (adapter_path / "adapter_model.safetensors").exists():
        log.error("LoRA adapter not found at %s", adapter_path)
        log.error("Run scripts/finetune_whisper_lora.py --provider %s first", provider_id)
        sys.exit(1)

    ct2_out = CT2_DIR / provider_id
    ct2_out.mkdir(parents=True, exist_ok=True)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    dtype  = torch.float16 if device == "cuda" else torch.float32

    # ── Step 1–3: merge LoRA into base model ─────────────────────────────────
    log.info("Loading base model %s …", BASE_MODEL)
    base = WhisperForConditionalGeneration.from_pretrained(
        BASE_MODEL, torch_dtype=dtype, device_map="auto" if device == "cuda" else None,
    )

    log.info("Loading LoRA adapter from %s …", adapter_path)
    peft_model = PeftModel.from_pretrained(base, str(adapter_path))

    log.info("Merging LoRA weights into base model …")
    merged = peft_model.merge_and_unload()          # returns plain HF model
    merged = merged.float()                          # ct2-converter needs fp32 input
    merged = merged.cpu()

    # ── Step 4: save merged HF model to temp dir ─────────────────────────────
    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_path = Path(tmp_dir) / "merged_hf"
        log.info("Saving merged model to %s …", tmp_path)
        merged.save_pretrained(str(tmp_path))
        del merged, peft_model, base

        # Copy tokenizer / processor config from adapter (it has the vocab files)
        log.info("Copying processor config …")
        processor = WhisperProcessor.from_pretrained(str(adapter_path))
        processor_out = ct2_out / "processor"
        processor_out.mkdir(exist_ok=True)
        processor.save_pretrained(str(processor_out))

        # ── Step 5: convert to CTranslate2 ───────────────────────────────────
        import subprocess
        cmd = [
            "ct2-transformers-converter",
            "--model", str(tmp_path),
            "--output_dir", str(ct2_out),
            "--quantization", quantization,
            "--force",
        ]
        log.info("Running: %s", " ".join(cmd))
        result = subprocess.run(cmd, capture_output=False)
        if result.returncode != 0:
            log.error("ct2-transformers-converter failed (exit %d)", result.returncode)
            sys.exit(1)

    import shutil as _shutil
    from huggingface_hub import hf_hub_download

    # Replace the vocabulary.json generated by ct2-transformers-converter.
    # The converter can produce incorrect timestamp token ordering which breaks
    # faster-whisper's special token lookup (e.g. <|startoftranscript|>).
    # LoRA does NOT change the vocabulary, so we use the reference Systran file.
    ref_vocab = hf_hub_download(
        repo_id="Systran/faster-whisper-large-v3",
        filename="vocabulary.json",
    )
    _shutil.copy2(ref_vocab, str(ct2_out / "vocabulary.json"))
    log.info("Replaced vocabulary.json with Systran/faster-whisper-large-v3 reference")

    # Copy tokenizer.json — faster-whisper needs it to decode special tokens
    # (e.g. <|startoftranscript|>). ct2-transformers-converter only writes
    # vocabulary.json (id→string mapping) which is not sufficient.
    tok_src = processor_out / "tokenizer.json"
    tok_dst = ct2_out / "tokenizer.json"
    if tok_src.exists():
        _shutil.copy2(str(tok_src), str(tok_dst))
        log.info("Copied tokenizer.json to CT2 root")

    # Copy preprocessor_config.json to CT2 root — faster-whisper reads it
    # to set the mel spectrogram feature size (128 for large-v3, not 80).
    # ct2-transformers-converter does not copy this file automatically.
    prep_src = processor_out / "preprocessor_config.json"
    prep_dst = ct2_out / "preprocessor_config.json"
    if prep_src.exists():
        _shutil.copy2(str(prep_src), str(prep_dst))
        log.info("Copied preprocessor_config.json to CT2 root (feature_size from processor)")
    else:
        log.warning(
            "preprocessor_config.json not found — faster-whisper may default "
            "to 80 mel bins; large-v3 requires 128"
        )

    log.info("CTranslate2 model saved to %s", ct2_out)
    log.info("Processor saved to %s", processor_out)

    # Verify key output files exist
    model_bin = ct2_out / "model.bin"
    config    = ct2_out / "config.json"
    if not model_bin.exists() or not config.exists():
        log.error("Export incomplete — expected model.bin and config.json in %s", ct2_out)
        sys.exit(1)

    size_mb = model_bin.stat().st_size / 1_048_576
    log.info("model.bin size: %.0f MB  (quantization=%s)", size_mb, quantization)
    return ct2_out


def main():
    parser = argparse.ArgumentParser(
        description="Export LoRA-merged Whisper model to CTranslate2 (faster-whisper) format"
    )
    parser.add_argument("--provider", required=True,
                        help="Provider ID (must have a trained LoRA in models/whisper_lora/)")
    parser.add_argument(
        "--quantization", default="float16",
        choices=["float32", "float16", "int8", "int8_float16"],
        help="CTranslate2 quantization level (default: float16)",
    )
    args = parser.parse_args()

    out = export(args.provider, quantization=args.quantization)
    print(f"\nExport complete: {out}")
    print("Update WhisperXLoRAServer to load from this path with faster_whisper.WhisperModel.")


if __name__ == "__main__":
    main()
