"""
tests/unit/test_provider_nginx_and_services.py — Tests for provider server
nginx configuration and NSSM service registration logic
(deploy/setup_provider_server.ps1 Steps 5/7 and 6/7).

Validates that:
- nginx config contains HTTPS on port 443 (Req 3.1)
- nginx config contains WebSocket upgrade headers for /ws/ (Req 3.4)
- nginx config contains X-Forwarded-Proto https (Req 3.5)
- nginx config contains rate limiting directives (Req 3.6)
- TLS cert paths appear correctly in nginx config (Req 3.2)
- NSSM registers two services with correct names (Req 4.1, 4.4)
- NSSM configures service dependency (Req 4.5)
- Self-signed cert generation produces valid paths (Req 3.3)
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Helpers — Python equivalents of the PowerShell nginx/NSSM logic
# ---------------------------------------------------------------------------


def generate_nginx_conf(tls_cert_path: str, tls_key_path: str) -> str:
    """
    Python equivalent of the PowerShell nginx.conf generator (Step 5/7).
    Generates an nginx configuration string with HTTPS, reverse proxy,
    WebSocket upgrade, X-Forwarded-Proto, and rate limiting.
    """
    # Normalize paths for nginx (forward slashes)
    cert = tls_cert_path.replace("\\", "/")
    key = tls_key_path.replace("\\", "/")

    return f"""\
# AI Scribe Provider Server - nginx configuration
# Generated by deploy/setup_provider_server.ps1

worker_processes auto;

events {{
    worker_connections 1024;
}}

http {{
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    # Rate limiting: 100 requests/second per client IP
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=100r/s;

    # Upstream backends
    upstream api_backend {{
        server 127.0.0.1:8000;
    }}

    upstream web_backend {{
        server 127.0.0.1:3000;
    }}

    # Redirect HTTP to HTTPS
    server {{
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }}

    # HTTPS server
    server {{
        listen 443 ssl;
        server_name _;

        # TLS configuration
        ssl_certificate     {cert};
        ssl_certificate_key {key};
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # WebSocket upgrade for /ws/ paths
        location /ws/ {{
            proxy_pass http://api_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_read_timeout 86400;
        }}

        # API reverse proxy
        location /api/ {{
            limit_req zone=api_limit burst=50 nodelay;
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }}

        # Web UI reverse proxy (default)
        location / {{
            proxy_pass http://web_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }}
    }}
}}
"""


def generate_self_signed_cert_paths(project_root: str) -> dict[str, str]:
    """
    Python equivalent of the self-signed certificate path generation.
    Returns the paths that would be created by the PowerShell script.
    """
    nginx_dir = os.path.join(project_root, "deploy", "nginx")
    ssl_dir = os.path.join(nginx_dir, "ssl")
    return {
        "pfx": os.path.join(ssl_dir, "ai-scribe.pfx"),
        "cert": os.path.join(ssl_dir, "ai-scribe.crt"),
        "key": os.path.join(ssl_dir, "ai-scribe.key"),
        "ssl_dir": ssl_dir,
        "nginx_dir": nginx_dir,
    }


def build_nssm_commands(project_root: str, node_exe: str = "node") -> list[dict]:
    """
    Python equivalent of the NSSM service registration commands (Step 6/7).
    Returns a list of NSSM command descriptors for both services.
    """
    uvicorn_exe = os.path.join(project_root, ".venv", "Scripts", "uvicorn.exe")
    web_app_dir = os.path.join(project_root, "client", "web")
    env_file = os.path.join(project_root, ".env.provider")

    commands = []

    # ai-scribe-api service
    commands.append({
        "action": "install",
        "service_name": "ai-scribe-api",
        "executable": uvicorn_exe,
        "app_parameters": "api.main:app --host 0.0.0.0 --port 8000",
        "app_directory": project_root,
        "start_type": "SERVICE_AUTO_START",
        "restart_delay": 5000,
        "env_file": env_file,
        "depends_on": None,
    })

    # ai-scribe-web service
    commands.append({
        "action": "install",
        "service_name": "ai-scribe-web",
        "executable": node_exe,
        "app_parameters": "node_modules/.bin/next start -p 3000",
        "app_directory": web_app_dir,
        "start_type": "SERVICE_AUTO_START",
        "restart_delay": 5000,
        "env_file": env_file,
        "depends_on": "ai-scribe-api",
    })

    return commands


# ---------------------------------------------------------------------------
# Tests — nginx HTTPS on port 443 (Req 3.1)
# ---------------------------------------------------------------------------

class TestNginxHttps:
    def test_listens_on_443_ssl(self):
        conf = generate_nginx_conf("/ssl/cert.pem", "/ssl/key.pem")
        assert "listen 443 ssl" in conf

    def test_redirects_http_to_https(self):
        conf = generate_nginx_conf("/ssl/cert.pem", "/ssl/key.pem")
        assert "listen 80" in conf
        assert "return 301 https://" in conf

    def test_reverse_proxy_to_api_8000(self):
        conf = generate_nginx_conf("/ssl/cert.pem", "/ssl/key.pem")
        assert "server 127.0.0.1:8000" in conf
        assert "location /api/" in conf

    def test_reverse_proxy_to_web_3000(self):
        conf = generate_nginx_conf("/ssl/cert.pem", "/ssl/key.pem")
        assert "server 127.0.0.1:3000" in conf
        assert "location /" in conf


# ---------------------------------------------------------------------------
# Tests — WebSocket upgrade headers for /ws/ (Req 3.4)
# ---------------------------------------------------------------------------

class TestNginxWebSocket:
    def test_ws_location_block_exists(self):
        conf = generate_nginx_conf("/ssl/c.pem", "/ssl/k.pem")
        assert "location /ws/" in conf

    def test_upgrade_header_present(self):
        conf = generate_nginx_conf("/ssl/c.pem", "/ssl/k.pem")
        assert 'proxy_set_header Upgrade' in conf
        assert 'proxy_set_header Connection "upgrade"' in conf

    def test_http_version_11_for_websocket(self):
        conf = generate_nginx_conf("/ssl/c.pem", "/ssl/k.pem")
        assert "proxy_http_version 1.1" in conf


# ---------------------------------------------------------------------------
# Tests — X-Forwarded-Proto https (Req 3.5)
# ---------------------------------------------------------------------------

class TestNginxForwardedProto:
    def test_x_forwarded_proto_in_ws(self):
        conf = generate_nginx_conf("/ssl/c.pem", "/ssl/k.pem")
        # Check that X-Forwarded-Proto https appears in the config
        assert "X-Forwarded-Proto https" in conf

    def test_x_forwarded_proto_in_api(self):
        conf = generate_nginx_conf("/ssl/c.pem", "/ssl/k.pem")
        # The directive should appear multiple times (ws, api, web locations)
        count = conf.count("X-Forwarded-Proto https")
        assert count >= 3, f"Expected at least 3 X-Forwarded-Proto directives, found {count}"


# ---------------------------------------------------------------------------
# Tests — Rate limiting directives (Req 3.6)
# ---------------------------------------------------------------------------

class TestNginxRateLimiting:
    def test_limit_req_zone_defined(self):
        conf = generate_nginx_conf("/ssl/c.pem", "/ssl/k.pem")
        assert "limit_req_zone" in conf

    def test_rate_100_per_second(self):
        conf = generate_nginx_conf("/ssl/c.pem", "/ssl/k.pem")
        assert "rate=100r/s" in conf

    def test_limit_req_applied_to_api(self):
        conf = generate_nginx_conf("/ssl/c.pem", "/ssl/k.pem")
        assert "limit_req zone=api_limit" in conf

    def test_binary_remote_addr_zone(self):
        conf = generate_nginx_conf("/ssl/c.pem", "/ssl/k.pem")
        assert "binary_remote_addr" in conf


# ---------------------------------------------------------------------------
# Tests — TLS cert paths in nginx config (Req 3.2)
# ---------------------------------------------------------------------------

class TestNginxTlsPaths:
    def test_cert_path_in_config(self):
        cert = "C:/certs/my-provider.crt"
        conf = generate_nginx_conf(cert, "/key.pem")
        assert f"ssl_certificate     {cert}" in conf

    def test_key_path_in_config(self):
        key = "C:/certs/my-provider.key"
        conf = generate_nginx_conf("/cert.pem", key)
        assert f"ssl_certificate_key {key}" in conf

    def test_backslash_paths_normalized(self):
        """Windows backslash paths should be converted to forward slashes."""
        cert = r"C:\nginx\ssl\cert.pem"
        key = r"C:\nginx\ssl\key.pem"
        conf = generate_nginx_conf(cert, key)
        assert "C:/nginx/ssl/cert.pem" in conf
        assert "C:/nginx/ssl/key.pem" in conf
        assert "\\" not in conf.split("ssl_certificate")[1].split("\n")[0]

    def test_arbitrary_paths_appear_verbatim(self):
        cert = "/opt/custom/location/server.crt"
        key = "/opt/custom/location/server.key"
        conf = generate_nginx_conf(cert, key)
        assert f"ssl_certificate     {cert}" in conf
        assert f"ssl_certificate_key {key}" in conf


# ---------------------------------------------------------------------------
# Tests — NSSM registers two services (Req 4.1, 4.4)
# ---------------------------------------------------------------------------

class TestNssmServiceRegistration:
    def test_two_services_registered(self):
        cmds = build_nssm_commands("/project")
        assert len(cmds) == 2

    def test_api_service_name(self):
        cmds = build_nssm_commands("/project")
        api = cmds[0]
        assert api["service_name"] == "ai-scribe-api"

    def test_web_service_name(self):
        cmds = build_nssm_commands("/project")
        web = cmds[1]
        assert web["service_name"] == "ai-scribe-web"

    def test_api_runs_uvicorn(self):
        cmds = build_nssm_commands("/project")
        api = cmds[0]
        assert "uvicorn" in api["executable"]
        assert "api.main:app" in api["app_parameters"]
        assert "--port 8000" in api["app_parameters"]

    def test_web_runs_node(self):
        cmds = build_nssm_commands("/project", node_exe="C:/nodejs/node.exe")
        web = cmds[1]
        assert web["executable"] == "C:/nodejs/node.exe"
        assert "next start" in web["app_parameters"]
        assert "-p 3000" in web["app_parameters"]

    def test_both_automatic_startup(self):
        cmds = build_nssm_commands("/project")
        for cmd in cmds:
            assert cmd["start_type"] == "SERVICE_AUTO_START"

    def test_both_5s_restart_delay(self):
        cmds = build_nssm_commands("/project")
        for cmd in cmds:
            assert cmd["restart_delay"] == 5000

    def test_both_load_env_from_env_provider(self):
        cmds = build_nssm_commands("/project")
        for cmd in cmds:
            assert cmd["env_file"].endswith(".env.provider")


# ---------------------------------------------------------------------------
# Tests — NSSM service dependency (Req 4.5)
# ---------------------------------------------------------------------------

class TestNssmServiceDependency:
    def test_web_depends_on_api(self):
        cmds = build_nssm_commands("/project")
        web = [c for c in cmds if c["service_name"] == "ai-scribe-web"][0]
        assert web["depends_on"] == "ai-scribe-api"

    def test_api_has_no_dependency(self):
        cmds = build_nssm_commands("/project")
        api = [c for c in cmds if c["service_name"] == "ai-scribe-api"][0]
        assert api["depends_on"] is None


# ---------------------------------------------------------------------------
# Tests — Self-signed cert generation paths (Req 3.3)
# ---------------------------------------------------------------------------

class TestSelfSignedCertPaths:
    def test_cert_path_under_ssl_dir(self):
        paths = generate_self_signed_cert_paths("/project")
        assert paths["cert"].endswith("ai-scribe.crt")
        assert "ssl" in paths["cert"]

    def test_key_path_under_ssl_dir(self):
        paths = generate_self_signed_cert_paths("/project")
        assert paths["key"].endswith("ai-scribe.key")
        assert "ssl" in paths["key"]

    def test_pfx_path_under_ssl_dir(self):
        paths = generate_self_signed_cert_paths("/project")
        assert paths["pfx"].endswith("ai-scribe.pfx")

    def test_ssl_dir_under_nginx_dir(self):
        paths = generate_self_signed_cert_paths("/project")
        assert paths["ssl_dir"].startswith(paths["nginx_dir"])

    def test_nginx_dir_under_deploy(self):
        paths = generate_self_signed_cert_paths("/project")
        assert os.path.join("deploy", "nginx") in paths["nginx_dir"]

    def test_paths_use_project_root(self):
        root = "C:\\Users\\admin\\ai-scribe"
        paths = generate_self_signed_cert_paths(root)
        for key in ("cert", "key", "pfx"):
            assert paths[key].startswith(root)


# ---------------------------------------------------------------------------
# Helper — Health check response validator (Python equivalent of PowerShell
# Test-HealthEndpoint logic)
# ---------------------------------------------------------------------------


def validate_health_response(response: object) -> bool:
    """
    Python equivalent of the PowerShell Test-HealthEndpoint response validator.
    Returns True iff the response is a dict-like object with a top-level
    "status" field whose value is exactly "ok".

    This mirrors the PowerShell logic:
        if ($response.status -eq "ok") { return $true }
        return $false
    """
    try:
        if isinstance(response, dict):
            return response.get("status") == "ok"
        return False
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Tests — Health check response validation (Req 5.1, 5.2, 5.3, 5.4, 5.5)
# ---------------------------------------------------------------------------

class TestHealthCheckValidation:
    """Tests for the health check response validator used in Step 7/7."""

    def test_status_ok_returns_true(self):
        """Response with {"status": "ok"} should return True."""
        assert validate_health_response({"status": "ok"}) is True

    def test_status_error_returns_false(self):
        """Response with {"status": "error"} should return False."""
        assert validate_health_response({"status": "error"}) is False

    def test_missing_status_field_returns_false(self):
        """Response with no status field should return False."""
        assert validate_health_response({"healthy": True}) is False

    def test_empty_dict_returns_false(self):
        """Empty response dict should return False."""
        assert validate_health_response({}) is False

    def test_connection_failure_returns_false(self):
        """Non-dict response (simulating connection failure / bad parse) returns False."""
        assert validate_health_response(None) is False

    def test_string_response_returns_false(self):
        """A plain string response should return False."""
        assert validate_health_response("ok") is False

    def test_status_ok_with_extra_fields(self):
        """Response with status ok plus extra fields should still return True."""
        assert validate_health_response({"status": "ok", "role": "provider-facing", "uptime": 123}) is True

    def test_status_none_returns_false(self):
        """Response with status: null should return False."""
        assert validate_health_response({"status": None}) is False

    def test_numeric_status_returns_false(self):
        """Response with numeric status should return False."""
        assert validate_health_response({"status": 200}) is False

    def test_list_response_returns_false(self):
        """A list response should return False."""
        assert validate_health_response([{"status": "ok"}]) is False
