"""
api/data_loader.py

Reads the output/ and ai-scribe-data/ directory structures to serve encounter
data via the FastAPI routes.  No database required — all data lives in Markdown
and JSON files generated by the pipeline.

New folder hierarchy (March 2026):
  ai-scribe-data/
    conversation/<physician>/<patient>_<eid>_<date>/
      patient_demographics.json, encounter_details.json,
      conversation_audio.mp3, note_audio.mp3, final_soap_note.md
    dictation/<physician>/<patient>_<eid>_<date>/
      patient_demographics.json, encounter_details.json,
      dictation.mp3, final_soap_note.md

  output/
    conversation/<physician>/<patient>_<eid>_<date>/
      generated_note_v{N}.md, comparison_v{N}.md, audio_transcript_v{N}.txt
    dictation/<physician>/<patient>_<eid>_<date>/
      ...
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional

import yaml

from config.paths import ROOT, OUTPUT_DIR, DATA_DIR, PROVIDERS_DIR

def _discover_versions() -> list[str]:
    """Return all versions found in output/ (highest first), purely from scanning files."""
    found: set[int] = set()
    if OUTPUT_DIR.exists():
        for mode_dir in OUTPUT_DIR.iterdir():
            if not mode_dir.is_dir():
                continue
            for physician_dir in mode_dir.iterdir():
                if not physician_dir.is_dir():
                    continue
                for enc_dir in physician_dir.iterdir():
                    if not enc_dir.is_dir():
                        continue
                    for f in enc_dir.glob("generated_note_v*.md"):
                        part = f.stem.split("_v")[-1]
                        if part.isdigit():
                            found.add(int(part))
    return [f"v{n}" for n in sorted(found, reverse=True)]


def get_versions() -> list[str]:
    """Return all known versions (highest first). Re-scans each call so new versions appear immediately."""
    return _discover_versions()


def get_latest_version() -> str:
    """Return the highest version string found dynamically, or 'v1' if no output exists."""
    versions = get_versions()
    return versions[0] if versions else "v1"


def resolve_version(version: str) -> str:
    """Resolve 'latest' to the actual latest version string. Pass-through for explicit versions."""
    if version == "latest":
        return get_latest_version()
    return version


# Sentinel used as default parameter in route signatures.
# Routes call resolve_version() to turn this into the real latest version.
LATEST_VERSION = "latest"

def _discover_sample_versions(out_dir: Path) -> list[str]:
    """Return versions available in a specific sample output directory (highest first)."""
    found: list[int] = []
    for f in out_dir.glob("generated_note_v*.md"):
        part = f.stem.split("_v")[-1]
        if part.isdigit():
            found.append(int(part))
    return [f"v{n}" for n in sorted(found, reverse=True)]


# The two top-level modes in the new data layout
_MODES = ("conversation", "dictation")


# ---------------------------------------------------------------------------
# Encounter discovery helpers
# ---------------------------------------------------------------------------

def _walk_encounters(base_dir: Path) -> list[tuple[str, str, str, Path]]:
    """
    Walk ai-scribe-data/ (or output/) and yield
    (mode, physician, sample_id, encounter_dir)
    for every encounter folder found.

    Layout: base_dir/<mode>/<physician>/<encounter_folder>/
    """
    results = []
    for mode in _MODES:
        mode_dir = base_dir / mode
        if not mode_dir.exists():
            continue
        for physician_dir in sorted(mode_dir.iterdir()):
            if not physician_dir.is_dir():
                continue
            physician = physician_dir.name
            for encounter_dir in sorted(physician_dir.iterdir()):
                if not encounter_dir.is_dir():
                    continue
                sample_id = encounter_dir.name
                results.append((mode, physician, sample_id, encounter_dir))
    return results


def _output_dir_for(sample_id: str) -> Optional[Path]:
    """Find the output directory for a given sample_id."""
    for mode, physician, sid, enc_dir in _walk_encounters(OUTPUT_DIR):
        if sid == sample_id:
            return enc_dir
    return None


def _data_dir_for(sample_id: str) -> Optional[tuple[str, str, Path]]:
    """Find (mode, physician, data_dir) for a sample_id in ai-scribe-data/."""
    for mode, physician, sid, enc_dir in _walk_encounters(DATA_DIR):
        if sid == sample_id:
            return mode, physician, enc_dir
    return None


# ---------------------------------------------------------------------------
# Sample discovery
# ---------------------------------------------------------------------------

def list_samples() -> list[dict]:
    """Return all samples found in output/ and ai-scribe-data/, with metadata.

    Samples from ai-scribe-data/ that don't have output yet still appear
    (with empty versions) so the UI can display all encounters.
    """
    seen: set[str] = set()
    samples = []

    # 1. Walk output/ first (these have generated notes)
    for mode, physician, sample_id, out_dir in _walk_encounters(OUTPUT_DIR):
        seen.add(sample_id)
        versions_available = _discover_sample_versions(out_dir)
        has_gold = _has_gold(sample_id)
        scores = _get_sample_scores(sample_id)
        display_mode = "ambient" if mode == "conversation" else "dictation"

        samples.append({
            "sample_id": sample_id,
            "mode": display_mode,
            "physician": physician,
            "versions": versions_available,
            "latest_version": versions_available[0] if versions_available else None,
            "has_gold": has_gold,
            "quality": scores,
            "is_test": _is_test_data(physician, sample_id),
        })

    # 2. Walk ai-scribe-data/ for encounters not yet in output/
    for mode, physician, sample_id, data_dir in _walk_encounters(DATA_DIR):
        if sample_id in seen:
            continue
        seen.add(sample_id)
        has_gold = (data_dir / "final_soap_note.md").exists()
        display_mode = "ambient" if mode == "conversation" else "dictation"

        samples.append({
            "sample_id": sample_id,
            "mode": display_mode,
            "physician": physician,
            "versions": [],
            "latest_version": None,
            "has_gold": has_gold,
            "quality": None,
            "is_test": _is_test_data(physician, sample_id),
        })

    return samples


def _is_test_data(physician: str, sample_id: str) -> bool:
    """Return True if this encounter is test data (not real patient data)."""
    return "test" in physician.lower() or "test" in sample_id.lower()


def _has_gold(sample_id: str) -> bool:
    result = _data_dir_for(sample_id)
    if result is None:
        return False
    _mode, _phys, data_dir = result
    return (data_dir / "final_soap_note.md").exists()


# ---------------------------------------------------------------------------
# Note / comparison / transcript content
# ---------------------------------------------------------------------------

def get_generated_note(sample_id: str, version: str = LATEST_VERSION) -> Optional[str]:
    version = resolve_version(version)
    out_dir = _output_dir_for(sample_id)
    if out_dir is None:
        return None
    path = out_dir / f"generated_note_{version}.md"
    return path.read_text() if path.exists() else None


def get_transcript(sample_id: str, version: str = LATEST_VERSION) -> Optional[str]:
    """Return the standalone transcript text for a sample + version."""
    version = resolve_version(version)
    out_dir = _output_dir_for(sample_id)
    if out_dir is None:
        return None
    path = out_dir / f"audio_transcript_{version}.txt"
    return path.read_text() if path.exists() else None


def list_transcript_versions(sample_id: str) -> list[str]:
    """Return all versions that have a standalone transcript file."""
    out_dir = _output_dir_for(sample_id)
    if out_dir is None:
        return []
    found: list[int] = []
    for f in out_dir.glob("audio_transcript_v*.txt"):
        part = f.stem.split("_v")[-1]
        if part.isdigit():
            found.append(int(part))
    return [f"v{n}" for n in sorted(found, reverse=True)]


def get_audio_path(sample_id: str) -> Optional[str]:
    """Return absolute path to the primary audio file for a sample (for streaming)."""
    result = _data_dir_for(sample_id)
    if result is None:
        return None
    mode, _phys, data_dir = result
    if mode == "conversation":
        # Primary = conversation audio; fallback to note audio
        conv = data_dir / "conversation_audio.mp3"
        note = data_dir / "note_audio.mp3"
        if conv.exists():
            return str(conv)
        if note.exists():
            return str(note)
    else:
        path = data_dir / "dictation.mp3"
        if path.exists():
            return str(path)
    return None


def get_audio_paths(sample_id: str) -> dict[str, Optional[str]]:
    """Return both audio paths for a sample (conversation mode has two)."""
    result = _data_dir_for(sample_id)
    if result is None:
        return {"primary": None, "note_dictation": None}
    mode, _phys, data_dir = result
    primary = None
    note_dictation = None
    if mode == "conversation":
        conv = data_dir / "conversation_audio.mp3"
        note = data_dir / "note_audio.mp3"
        if conv.exists():
            primary = str(conv)
        if note.exists():
            note_dictation = str(note)
        # Fallback: if only note exists, use as primary
        if primary is None and note_dictation is not None:
            primary = note_dictation
            note_dictation = None
    else:
        path = data_dir / "dictation.mp3"
        if path.exists():
            primary = str(path)
    return {"primary": primary, "note_dictation": note_dictation}


def get_comparison(sample_id: str, version: str = LATEST_VERSION) -> Optional[str]:
    version = resolve_version(version)
    out_dir = _output_dir_for(sample_id)
    if out_dir is None:
        return None
    path = out_dir / f"comparison_{version}.md"
    return path.read_text() if path.exists() else None


def get_gold_note(sample_id: str) -> Optional[str]:
    result = _data_dir_for(sample_id)
    if result is None:
        return None
    _mode, _phys, data_dir = result
    path = data_dir / "final_soap_note.md"
    return path.read_text() if path.exists() else None


def get_patient_context(sample_id: str) -> Optional[dict]:
    """
    Load patient context from the new JSON files:
      patient_demographics.json  +  encounter_details.json

    Returns a unified dict matching the old patient_context.yaml shape
    so the UI and pipeline continue to work unchanged.
    """
    result = _data_dir_for(sample_id)
    if result is None:
        return None
    _mode, _phys, data_dir = result

    demo_path = data_dir / "patient_demographics.json"
    enc_path = data_dir / "encounter_details.json"

    if not demo_path.exists() and not enc_path.exists():
        return None

    demo = {}
    enc = {}
    if demo_path.exists():
        demo = json.loads(demo_path.read_text())
    if enc_path.exists():
        enc = json.loads(enc_path.read_text())

    # Build a unified context dict compatible with existing UI expectations
    provider = enc.get("provider", {})
    return {
        "patient": {
            "name": f"{demo.get('first_name', '')} {demo.get('last_name', '')}".strip() or None,
            "date_of_birth": demo.get("date_of_birth"),
            "sex": None,  # not in new demographics JSON
            "mrn": demo.get("record_number"),
        },
        "encounter": {
            "date_of_service": enc.get("date_of_exam"),
            "visit_type": enc.get("visit_type"),
            "date_of_injury": enc.get("date_of_accident") or None,
            "case_number": enc.get("case_number") or None,
            "encounter_id": enc.get("encounter_id"),
            "mode": enc.get("mode"),
            "location": enc.get("location"),
        },
        "provider": {
            "name": provider.get("full_name"),
            "credentials": None,
            "specialty": None,
        },
        "facility": {
            "name": None,
            "location": enc.get("location"),
        },
    }


def get_mode(sample_id: str) -> str:
    result = _data_dir_for(sample_id)
    if result is not None:
        mode, _phys, _dir = result
        return "ambient" if mode == "conversation" else "dictation"
    # Fallback: check output dir
    for mode, _phys, sid, _dir in _walk_encounters(OUTPUT_DIR):
        if sid == sample_id:
            return "ambient" if mode == "conversation" else "dictation"
    return "dictation"


# ---------------------------------------------------------------------------
# Quality data
# ---------------------------------------------------------------------------

# Cache parsed quality report to avoid re-reading on every request
_quality_cache: dict[str, dict] = {}


def clear_quality_cache(version: str | None = None) -> None:
    """Invalidate quality report cache. Call after quality sweep generates new reports."""
    if version:
        _quality_cache.pop(version, None)
    else:
        _quality_cache.clear()


def _parse_quality_report(version: str = LATEST_VERSION) -> dict[str, dict]:
    """Parse output/quality_report_{version}.md → {sample_id: {scores}}."""
    version = resolve_version(version)
    if version in _quality_cache:
        return _quality_cache[version]

    path = OUTPUT_DIR / f"quality_report_{version}.md"
    if not path.exists():
        return {}

    text = path.read_text()
    result: dict[str, dict] = {}

    for line in text.splitlines():
        if not line.startswith("|") or "---" in line or "Sample" in line:
            continue
        parts = [p.strip() for p in line.strip("|").split("|")]
        if len(parts) < 7:
            continue
        sample_id = parts[0]
        if not sample_id or sample_id == "Sample":
            continue
        try:
            result[sample_id] = {
                "overall": float(parts[1]) if parts[1] and parts[1] != "—" else None,
                "accuracy": float(parts[2]) if parts[2] and parts[2] != "—" else None,
                "completeness": float(parts[3]) if parts[3] and parts[3] != "—" else None,
                "no_hallucination": float(parts[4]) if parts[4] and parts[4] != "—" else None,
                "structure": float(parts[5]) if parts[5] and parts[5] != "—" else None,
                "language": float(parts[6]) if parts[6] and parts[6] != "—" else None,
                "overlap": parts[7].replace("%", "") if len(parts) > 7 and "%" in parts[7] else None,
            }
        except (ValueError, IndexError):
            continue

    _quality_cache[version] = result
    return result


def _get_sample_scores(sample_id: str, version: str = LATEST_VERSION) -> Optional[dict]:
    version = resolve_version(version)
    scores = _parse_quality_report(version)
    return scores.get(sample_id)


def get_aggregate_quality(version: str = LATEST_VERSION) -> dict:
    """Return aggregate quality stats for all samples."""
    version = resolve_version(version)
    scores_map = _parse_quality_report(version)
    if not scores_map:
        return {}

    all_scores = [v["overall"] for v in scores_map.values() if v.get("overall")]
    if not all_scores:
        return {}

    dims = ["accuracy", "completeness", "no_hallucination", "structure", "language"]
    dim_avgs = {}
    for d in dims:
        vals = [v[d] for v in scores_map.values() if v.get(d)]
        dim_avgs[d] = round(sum(vals) / len(vals), 3) if vals else None

    return {
        "version": version,
        "sample_count": len(all_scores),
        "average": round(sum(all_scores) / len(all_scores), 3),
        "min": min(all_scores),
        "max": max(all_scores),
        "dimensions": dim_avgs,
    }


def get_quality_by_version() -> list[dict]:
    """Return quality trend across all available versions."""
    trend = []
    for v in reversed(get_versions()):  # v1 → v7 order
        agg = get_aggregate_quality(v)
        if agg:
            trend.append(agg)
    return trend


def get_aggregate_quality_by_mode(version: str = LATEST_VERSION) -> dict:
    """Return aggregate quality stats broken down by dictation vs ambient."""
    version = resolve_version(version)
    scores_map = _parse_quality_report(version)
    if not scores_map:
        return {}

    samples_list = list_samples()
    sample_modes = {s["sample_id"]: s["mode"] for s in samples_list}

    result = {}
    for mode_label in ("dictation", "ambient"):
        mode_scores = {
            sid: sc for sid, sc in scores_map.items()
            if sample_modes.get(sid) == mode_label and sc.get("overall")
        }
        if not mode_scores:
            continue
        all_overall = [sc["overall"] for sc in mode_scores.values()]
        dims = ["accuracy", "completeness", "no_hallucination", "structure", "language"]
        dim_avgs = {}
        for d in dims:
            vals = [sc[d] for sc in mode_scores.values() if sc.get(d)]
            dim_avgs[d] = round(sum(vals) / len(vals), 3) if vals else None

        result[mode_label] = {
            "version": version,
            "sample_count": len(all_overall),
            "average": round(sum(all_overall) / len(all_overall), 3),
            "min": min(all_overall),
            "max": max(all_overall),
            "dimensions": dim_avgs,
        }
    return result


def get_aggregate_quality_by_provider(version: str = LATEST_VERSION) -> list[dict]:
    """Return aggregate quality per provider."""
    version = resolve_version(version)
    scores_map = _parse_quality_report(version)
    if not scores_map:
        return []

    samples_list = list_samples()
    # Group samples by physician
    physician_samples: dict[str, list[str]] = {}
    for s in samples_list:
        phys = s.get("physician", "unknown")
        physician_samples.setdefault(phys, []).append(s["sample_id"])

    result = []
    for phys, sample_ids in sorted(physician_samples.items()):
        phys_scores = [
            scores_map[sid]["overall"]
            for sid in sample_ids
            if sid in scores_map and scores_map[sid].get("overall")
        ]
        if not phys_scores:
            continue
        display_name = phys.replace("_", " ").title()
        result.append({
            "provider_id": phys,
            "provider_name": display_name,
            "sample_count": len(phys_scores),
            "average": round(sum(phys_scores) / len(phys_scores), 3),
            "min": min(phys_scores),
            "max": max(phys_scores),
        })
    return result


def get_all_sample_scores(version: str = LATEST_VERSION) -> list[dict]:
    """Return per-sample scores as a list for the samples table."""
    version = resolve_version(version)
    scores_map = _parse_quality_report(version)
    result = []
    for sample_id, scores in scores_map.items():
        mode = get_mode(sample_id)
        result.append({"sample_id": sample_id, "mode": mode, "version": version, **scores})
    return result


# ---------------------------------------------------------------------------
# Batch report stats
# ---------------------------------------------------------------------------

_batch_cache: dict[str, dict] = {}


def get_batch_stats(version: str = LATEST_VERSION) -> dict:
    """Parse output/batch_report_{version}.md for pipeline stats."""
    version = resolve_version(version)
    if version in _batch_cache:
        return _batch_cache[version]

    path = OUTPUT_DIR / f"batch_report_{version}.md"
    if not path.exists():
        return {}

    text = path.read_text()
    stats: dict = {"version": version, "samples": []}

    m = re.search(r"\*\*Samples:\*\*\s*(\d+)", text)
    if m:
        stats["total_samples"] = int(m.group(1))

    m = re.search(r"\*\*Avg per sample:\*\*\s*([\d.]+)s", text)
    if m:
        stats["avg_time_s"] = float(m.group(1))

    for line in text.splitlines():
        if not line.startswith("|") or "---" in line or "Sample" in line:
            continue
        parts = [p.strip() for p in line.strip("|").split("|")]
        if len(parts) < 8:
            continue
        sample_id = parts[0]
        if not sample_id:
            continue
        try:
            stats["samples"].append({
                "sample_id": sample_id,
                "mode": parts[1],
                "duration_s": float(parts[3].rstrip("s")) if parts[3].rstrip("s").replace(".", "").isdigit() else None,
                "asr_ms": int(parts[4]) if parts[4].isdigit() else None,
                "llm_ms": int(parts[5]) if parts[5].isdigit() else None,
                "asr_conf": float(parts[6]) if parts[6].replace(".", "").isdigit() else None,
                "note_conf": float(parts[7]) if parts[7].replace(".", "").isdigit() else None,
            })
        except (ValueError, IndexError):
            continue

    _batch_cache[version] = stats
    return stats


# ---------------------------------------------------------------------------
# Provider data
# ---------------------------------------------------------------------------

def list_providers() -> list[dict]:
    """List all providers — from YAML profiles AND from data directory physicians."""
    seen: set[str] = set()
    result = []

    # 1. Providers with YAML profiles
    if PROVIDERS_DIR.exists():
        for yaml_path in sorted(PROVIDERS_DIR.glob("*.yaml")):
            with open(yaml_path) as f:
                data = yaml.safe_load(f)
            result.append(_summarize_provider(data))
            seen.add(data.get("id", yaml_path.stem))

    # 2. Discover physicians from data directories that don't have profiles
    for base_dir in (DATA_DIR, OUTPUT_DIR):
        if not base_dir.exists():
            continue
        for mode in _MODES:
            mode_dir = base_dir / mode
            if not mode_dir.exists():
                continue
            for physician_dir in sorted(mode_dir.iterdir()):
                if not physician_dir.is_dir():
                    continue
                pid = physician_dir.name
                if pid in seen:
                    continue
                seen.add(pid)
                display_name = pid.replace("_", " ").title()
                result.append({
                    "id": pid,
                    "name": display_name,
                    "credentials": None,
                    "specialty": None,
                    "latest_score": None,
                    "quality_scores": {},
                })

    # Attach avg quality scores for all providers from latest quality report
    scores_map = _parse_quality_report("latest")
    if scores_map:
        samples_list = list_samples()
        for provider in result:
            pid = provider["id"]
            provider_sample_ids = [s["sample_id"] for s in samples_list if s.get("physician") == pid]
            provider_scores = [
                scores_map[sid]["overall"]
                for sid in provider_sample_ids
                if sid in scores_map and scores_map[sid].get("overall")
            ]
            if provider_scores and provider.get("latest_score") is None:
                provider["latest_score"] = round(sum(provider_scores) / len(provider_scores), 2)

    return result


def get_provider(provider_id: str) -> Optional[dict]:
    path = PROVIDERS_DIR / f"{provider_id}.yaml"
    if not path.exists():
        return None
    with open(path) as f:
        return yaml.safe_load(f)


def _summarize_provider(data: dict) -> dict:
    latest_score = None
    if data.get("quality_scores"):
        scores = data["quality_scores"]
        for v in get_versions():
            if v in scores:
                latest_score = scores[v]
                break
    return {
        "id": data.get("id"),
        "name": data.get("name"),
        "credentials": data.get("credentials"),
        "specialty": data.get("specialty"),
        "latest_score": latest_score,
        "quality_scores": data.get("quality_scores", {}),
    }
