"""
api/data_loader.py

Reads the output/ and data/ directory structure to serve encounter data
via the FastAPI routes. No database required — all data lives in Markdown
and YAML files generated by the pipeline.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

import yaml

# Repository root (two levels up from this file)
ROOT = Path(__file__).parent.parent
OUTPUT_DIR = ROOT / "output"
DATA_DIR = ROOT / "data"
PROVIDERS_DIR = ROOT / "config" / "providers"

VERSIONS = ["v6", "v5", "v4", "v3", "v2", "v1"]
LATEST_VERSION = "v6"


# ---------------------------------------------------------------------------
# Sample discovery
# ---------------------------------------------------------------------------

def _mode_for(output_subdir: str) -> str:
    """Map output subdirectory name → mode label."""
    return "dictation" if "dictation" in output_subdir else "ambient"


def _data_subdir(mode: str) -> str:
    return "dictation" if mode == "dictation" else "conversations"


def list_samples() -> list[dict]:
    """Return all samples found in output/, with metadata."""
    samples = []

    for subdir in ("dictation", "conversations"):
        base = OUTPUT_DIR / subdir
        if not base.exists():
            continue
        for sample_dir in sorted(base.iterdir()):
            if not sample_dir.is_dir():
                continue
            sample_id = sample_dir.name
            mode = _mode_for(subdir)

            # Determine which versions exist
            versions_available = [
                v for v in VERSIONS
                if (sample_dir / f"generated_note_{v}.md").exists()
            ]
            has_gold = _has_gold(sample_id, mode)

            # Quality scores from latest quality report
            scores = _get_sample_scores(sample_id)

            samples.append({
                "sample_id": sample_id,
                "mode": mode,
                "versions": versions_available,
                "latest_version": versions_available[0] if versions_available else None,
                "has_gold": has_gold,
                "quality": scores,
            })

    return samples


def _has_gold(sample_id: str, mode: str) -> bool:
    data_base = DATA_DIR / _data_subdir(mode)
    return (
        (data_base / sample_id / "soap_final.md").exists()
        or (data_base / sample_id / "soap_initial.md").exists()
    )


# ---------------------------------------------------------------------------
# Note / comparison / transcript content
# ---------------------------------------------------------------------------

def get_generated_note(sample_id: str, version: str = LATEST_VERSION) -> Optional[str]:
    for subdir in ("dictation", "conversations"):
        path = OUTPUT_DIR / subdir / sample_id / f"generated_note_{version}.md"
        if path.exists():
            return path.read_text()
    return None


def get_transcript(sample_id: str, version: str = LATEST_VERSION) -> Optional[str]:
    """Return the standalone transcript text for a sample + version."""
    for subdir in ("dictation", "conversations"):
        path = OUTPUT_DIR / subdir / sample_id / f"audio_transcript_{version}.txt"
        if path.exists():
            return path.read_text()
    return None


def list_transcript_versions(sample_id: str) -> list[str]:
    """Return all versions that have a standalone transcript file."""
    for subdir in ("dictation", "conversations"):
        sample_dir = OUTPUT_DIR / subdir / sample_id
        if sample_dir.exists():
            versions = []
            for v in VERSIONS:
                if (sample_dir / f"audio_transcript_{v}.txt").exists():
                    versions.append(v)
            return versions
    return []


def get_audio_path(sample_id: str) -> Optional[str]:
    """Return absolute path to the audio file for a sample (for streaming)."""
    for subdir, audio_name in (("dictation", "dictation.mp3"), ("conversations", "conversation.mp3")):
        path = DATA_DIR / subdir / sample_id / audio_name
        if path.exists():
            return str(path)
    return None


def get_comparison(sample_id: str, version: str = LATEST_VERSION) -> Optional[str]:
    for subdir in ("dictation", "conversations"):
        path = OUTPUT_DIR / subdir / sample_id / f"comparison_{version}.md"
        if path.exists():
            return path.read_text()
    return None


def get_gold_note(sample_id: str) -> Optional[str]:
    for mode, subdir in (("dictation", "dictation"), ("ambient", "conversations")):
        base = DATA_DIR / subdir / sample_id
        for fname in ("soap_final.md", "soap_initial.md"):
            path = base / fname
            if path.exists():
                return path.read_text()
    return None


def get_patient_context(sample_id: str) -> Optional[dict]:
    for subdir in ("dictation", "conversations"):
        path = DATA_DIR / subdir / sample_id / "patient_context.yaml"
        if path.exists():
            with open(path) as f:
                return yaml.safe_load(f)
    return None


def get_mode(sample_id: str) -> str:
    if (OUTPUT_DIR / "dictation" / sample_id).exists():
        return "dictation"
    return "ambient"


# ---------------------------------------------------------------------------
# Quality data
# ---------------------------------------------------------------------------

# Cache parsed quality report to avoid re-reading on every request
_quality_cache: dict[str, dict] = {}


def _parse_quality_report(version: str = LATEST_VERSION) -> dict[str, dict]:
    """Parse output/quality_report_{version}.md → {sample_id: {scores}}."""
    if version in _quality_cache:
        return _quality_cache[version]

    path = OUTPUT_DIR / f"quality_report_{version}.md"
    if not path.exists():
        return {}

    text = path.read_text()
    result: dict[str, dict] = {}

    # Parse the per-sample table
    # | Sample | Overall | Accuracy | Complete | No Halluc | Structure | Language | Overlap | Status |
    for line in text.splitlines():
        if not line.startswith("|") or "---" in line or "Sample" in line:
            continue
        parts = [p.strip() for p in line.strip("|").split("|")]
        if len(parts) < 7:
            continue
        sample_id = parts[0]
        if not sample_id or sample_id == "Sample":
            continue
        try:
            result[sample_id] = {
                "overall": float(parts[1]) if parts[1] and parts[1] != "—" else None,
                "accuracy": float(parts[2]) if parts[2] and parts[2] != "—" else None,
                "completeness": float(parts[3]) if parts[3] and parts[3] != "—" else None,
                "no_hallucination": float(parts[4]) if parts[4] and parts[4] != "—" else None,
                "structure": float(parts[5]) if parts[5] and parts[5] != "—" else None,
                "language": float(parts[6]) if parts[6] and parts[6] != "—" else None,
                "overlap": parts[7].replace("%", "") if len(parts) > 7 and "%" in parts[7] else None,
            }
        except (ValueError, IndexError):
            continue

    _quality_cache[version] = result
    return result


def _get_sample_scores(sample_id: str, version: str = LATEST_VERSION) -> Optional[dict]:
    scores = _parse_quality_report(version)
    return scores.get(sample_id)


def get_aggregate_quality(version: str = LATEST_VERSION) -> dict:
    """Return aggregate quality stats for all samples."""
    scores_map = _parse_quality_report(version)
    if not scores_map:
        return {}

    all_scores = [v["overall"] for v in scores_map.values() if v.get("overall")]
    if not all_scores:
        return {}

    dims = ["accuracy", "completeness", "no_hallucination", "structure", "language"]
    dim_avgs = {}
    for d in dims:
        vals = [v[d] for v in scores_map.values() if v.get(d)]
        dim_avgs[d] = round(sum(vals) / len(vals), 3) if vals else None

    return {
        "version": version,
        "sample_count": len(all_scores),
        "average": round(sum(all_scores) / len(all_scores), 3),
        "min": min(all_scores),
        "max": max(all_scores),
        "dimensions": dim_avgs,
    }


def get_quality_by_version() -> list[dict]:
    """Return quality trend across all available versions."""
    trend = []
    for v in reversed(VERSIONS):  # v1 → v4 order
        agg = get_aggregate_quality(v)
        if agg:
            trend.append(agg)
    return trend


def get_all_sample_scores(version: str = LATEST_VERSION) -> list[dict]:
    """Return per-sample scores as a list for the samples table."""
    scores_map = _parse_quality_report(version)
    result = []
    for sample_id, scores in scores_map.items():
        mode = get_mode(sample_id)
        result.append({"sample_id": sample_id, "mode": mode, "version": version, **scores})
    return result


# ---------------------------------------------------------------------------
# Batch report stats
# ---------------------------------------------------------------------------

_batch_cache: dict[str, dict] = {}


def get_batch_stats(version: str = LATEST_VERSION) -> dict:
    """Parse output/batch_report_{version}.md for pipeline stats."""
    if version in _batch_cache:
        return _batch_cache[version]

    path = OUTPUT_DIR / f"batch_report_{version}.md"
    if not path.exists():
        return {}

    text = path.read_text()
    stats: dict = {"version": version, "samples": []}

    # Header line: **Samples:** 33 (21 dictation, 12 ambient)
    m = re.search(r"\*\*Samples:\*\*\s*(\d+)", text)
    if m:
        stats["total_samples"] = int(m.group(1))

    m = re.search(r"\*\*Avg per sample:\*\*\s*([\d.]+)s", text)
    if m:
        stats["avg_time_s"] = float(m.group(1))

    # Per-sample table rows
    for line in text.splitlines():
        if not line.startswith("|") or "---" in line or "Sample" in line:
            continue
        parts = [p.strip() for p in line.strip("|").split("|")]
        if len(parts) < 8:
            continue
        sample_id = parts[0]
        if not sample_id:
            continue
        try:
            stats["samples"].append({
                "sample_id": sample_id,
                "mode": parts[1],
                "duration_s": float(parts[3].rstrip("s")) if parts[3].rstrip("s").replace(".", "").isdigit() else None,
                "asr_ms": int(parts[4]) if parts[4].isdigit() else None,
                "llm_ms": int(parts[5]) if parts[5].isdigit() else None,
                "asr_conf": float(parts[6]) if parts[6].replace(".", "").isdigit() else None,
                "note_conf": float(parts[7]) if parts[7].replace(".", "").isdigit() else None,
            })
        except (ValueError, IndexError):
            continue

    _batch_cache[version] = stats
    return stats


# ---------------------------------------------------------------------------
# Provider data
# ---------------------------------------------------------------------------

def list_providers() -> list[dict]:
    if not PROVIDERS_DIR.exists():
        return []
    result = []
    for yaml_path in sorted(PROVIDERS_DIR.glob("*.yaml")):
        with open(yaml_path) as f:
            data = yaml.safe_load(f)
        result.append(_summarize_provider(data))
    return result


def get_provider(provider_id: str) -> Optional[dict]:
    path = PROVIDERS_DIR / f"{provider_id}.yaml"
    if not path.exists():
        return None
    with open(path) as f:
        return yaml.safe_load(f)


def _summarize_provider(data: dict) -> dict:
    latest_score = None
    if data.get("quality_scores"):
        scores = data["quality_scores"]
        for v in VERSIONS:
            if v in scores:
                latest_score = scores[v]
                break
    return {
        "id": data.get("id"),
        "name": data.get("name"),
        "credentials": data.get("credentials"),
        "specialty": data.get("specialty"),
        "latest_score": latest_score,
        "quality_scores": data.get("quality_scores", {}),
    }
